EN.SuperRestaurant.MVC/Controllers/MealsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EN.SuperRestaurant.Entities.Meals;
using EN.SuperRestaurant.MVC.Data;
using AutoMapper;
using EN.SuperRestaurant.MVC.Models.Meals;
using Microsoft.AspNetCore.Mvc.Rendering;
using EN.SuperRestaurant.Entities.Ingredients;

namespace EN.SuperRestaurant.MVC.Controllers
{
    public class MealsController : Controller
    {
        #region Data and Const

        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public MealsController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        #endregion

        #region Actions

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var meals = await _context
                                .Meals
                                .ToListAsync();

            var mealVMs = _mapper.Map<List<MealViewModel>>(meals);

            return View(mealVMs);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context
                                .Meals
                                .Include(meal => meal.Ingredients)
                                .Where(meal => meal.Id == id)
                                .SingleOrDefaultAsync();

            if (meal == null)
            {
                return NotFound();
            }

            var mealVM = _mapper.Map<MealDetailsViewModel>(meal);

            return View(mealVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var createUpdateMealVM = new CreateUpdateMealViewModel();
            createUpdateMealVM.IngredientLookup = new MultiSelectList(_context.Ingredients, "Id", "Name");

            return View(createUpdateMealVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateUpdateMealViewModel createUpdateMealViewModel)
        {
            if (ModelState.IsValid)
            {
                // Transform createUpdateMealViewModel -> Meal
                var meal = _mapper.Map<Meal>(createUpdateMealViewModel);

                // Update Meal Ingredients
                await UpdateMealIngredients(meal, createUpdateMealViewModel.IngredientIds);

                // Update Meal Price
                meal.Price = GetMealPrice(meal.Ingredients);

                _context.Add(meal);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(createUpdateMealViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context
                                .Meals
                                .Include(meal => meal.Ingredients)
                                .Where(meal => meal.Id == id)
                                .SingleOrDefaultAsync();

            if (meal == null)
            {
                return NotFound();
            }

            var mealVM = _mapper.Map<CreateUpdateMealViewModel>(meal);

            mealVM.IngredientLookup = new MultiSelectList(_context.Ingredients, "Id", "Name");

            return View(mealVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateUpdateMealViewModel createUpdateMealViewModel)
        {
            if (id != createUpdateMealViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Get the meal including ingredients from the DB
                var meal = await  _context
                                    .Meals
                                    .Include(meal => meal.Ingredients)
                                    .Where(meal => meal.Id == id)
                                    .SingleOrDefaultAsync();

                if (meal == null)
                {
                    return NotFound();
                }

                // Patch the meal from the createUpdateMealViewModel
                _mapper.Map(createUpdateMealViewModel, meal);

                // UpdateMealIngredients
                await UpdateMealIngredients(meal, createUpdateMealViewModel.IngredientIds);

                // Update the price of the meal
                meal.Price = GetMealPrice(meal.Ingredients);

                try
                {
                    _context.Update(meal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MealExists(createUpdateMealViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(createUpdateMealViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meal = await _context.Meals.FindAsync(id);
            if (meal != null)
            {
                _context.Meals.Remove(meal);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Private Methods

        private bool MealExists(int id)
        {
            return _context.Meals.Any(e => e.Id == id);
        }

        private async Task UpdateMealIngredients(Meal meal, List<int> ingredientIds)
        {
            // Clear meal ingredients
            meal.Ingredients.Clear();

            // Get ingredients from DB using the ingredientIds
            var ingredients = await _context
                                        .Ingredients
                                        .Where(ingredient => ingredientIds.Contains(ingredient.Id))
                                        .ToListAsync();

            // Add ingredients to Meal.Ingredients
            meal.Ingredients.AddRange(ingredients);
        }

        private decimal GetMealPrice(List<Ingredient> ingredients)
        {
            var mealPrice = ingredients.Sum(ingredient => ingredient.Price);
            var mealPriceWithProfit = mealPrice * 1.4m;

            return mealPriceWithProfit;
        }

        #endregion
    }
}

EN.SuperRestaurant.MVC/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EN.SuperRestaurant.Entities.Orders;
using EN.SuperRestaurant.MVC.Data;
using AutoMapper;
using EN.SuperRestaurant.MVC.Models.Orders;
using EN.SuperRestaurant.Entities.Meals;

namespace EN.SuperRestaurant.MVC.Controllers
{
    public class OrdersController : Controller
    {
        #region Data and Const

        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public OrdersController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        #endregion

        #region Actions

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var orders = await _context
                                .Orders
                                .Include(order => order.Customer)
                                .ToListAsync();

            var orderVMs = _mapper.Map<List<OrderViewModel>>(orders);

            return View(orderVMs);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context
                                .Orders
                                .Include(order => order.Customer)
                                .Include(order => order.Meals)
                                .Where(order => order.Id == id)
                                .SingleOrDefaultAsync();

            if (order == null)
            {
                return NotFound();
            }

            var orderDetailsVM = _mapper.Map<OrderDetailsViewModel>(order);

            return View(orderDetailsVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var createUpdateOrderVM = new CreateOrderViewModel();

            createUpdateOrderVM.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            createUpdateOrderVM.MealLookup = new MultiSelectList(_context.Meals, "Id", "Name");

            return View(createUpdateOrderVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateOrderViewModel createOrderVM)
        {
            if (ModelState.IsValid)
            {
                var order = _mapper.Map<Order>(createOrderVM);

                order.OrderTime = DateTime.Now;

                await UpdateOrderMeals(order, createOrderVM.MealIds);

                order.TotalPrice = GetOrderTotalPrice(order.Meals);

                _context.Add(order);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            createOrderVM.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            createOrderVM.MealLookup = new MultiSelectList(_context.Meals, "Id", "Name");

            return View(createOrderVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context
                                    .Orders
                                    .Include(order => order.Meals)
                                    .Where(order => order.Id == id)
                                    .SingleOrDefaultAsync();

            if (order == null)
            {
                return NotFound();
            }

            var updateOrderVM = _mapper.Map<UpdateOrderViewModel>(order);

            updateOrderVM.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            updateOrderVM.MealLookup = new MultiSelectList(_context.Meals, "Id", "Name");

            return View(updateOrderVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UpdateOrderViewModel updateViewModel)
        {
            if (id != updateViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Get the order including meals from the DB
                var order = await _context
                                    .Orders
                                    .Include(order => order.Meals)
                                    .Where(order => order.Id == id)
                                    .SingleOrDefaultAsync();

                if (order == null)
                {
                    return NotFound();
                }

                // Patch the order
                _mapper.Map(updateViewModel, order);

                // Update order meals
                await UpdateOrderMeals(order, updateViewModel.MealIds);

                // Update order total price
                order.TotalPrice = GetOrderTotalPrice(order.Meals);

                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(updateViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }


            updateViewModel.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            updateViewModel.MealLookup = new MultiSelectList(_context.Meals, "Id", "Name");

            return View(updateViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Private Methods

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }

        private async Task UpdateOrderMeals(Order order, List<int> mealIds)
        {
            // Clear Order.Meal
            order.Meals.Clear();

            // Load Meals from MealIds
            var meals = await _context
                                .Meals
                                .Where(meal => mealIds.Contains(meal.Id))
                                .ToListAsync();

            // Add Meals to Order
            order.Meals.AddRange(meals);
        }

        private decimal GetOrderTotalPrice(List<Meal> meals)
        {
            var mealsPrice = meals.Sum(meal => meal.Price);
            var mealsPriceWithVAT = mealsPrice * 1.16m;

            return mealsPriceWithVAT;
        }

        #endregion

    }
}

EN.SuperRestaurant.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Super RestaurantC</title>

    <link rel="icon" type="image/x-icon" href="~/imgs/logo.png">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/2.1.3/css/dataTables.bootstrap5.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom shadow-sm mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/imgs/logo.png" alt="Logo" height="30" />
                    Restaurant
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Ingredients" asp-action="Index">
                                Ingredients
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Customers" asp-action="Index">
                                Customers
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Meals" asp-action="Index">
                                Meals
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Orders" asp-action="Index">
                                Orders
                            </a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer>

        <div class="site-map">

            <div class="container py-5">

                <div class="row g-4">

                    <div class="col-lg-6 col-xl-3">

                        <div class="text-body-secondary">
                            <h3 class="text-dark">SimTaxi</h3>
                            <div>Main Street</div>
                            <div>Amman, Sports Circle</div>
                            <div>Jordan</div>

                            <div class="mt-4">
                                <label for="phone" class="fw-bold">Phone:</label>
                                <a id="phone" class="text-decoration-none text-danger a-hover"
                                    href="tel:+96277788899">+96277788899</a>
                            </div>
                            <div>
                                <label for="email" class="fw-bold">Email:</label>
                                <a id="email" class="text-decoration-none text-danger a-hover"
                                    href="mailto:info@example.com">info@example.com</a>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-6 col-xl-3">

                        <h6 class="fw-bold mb-3">Useful Links</h6>

                        <ul class="nav flex-column">
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Home
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    About Us
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Services
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Term of Service
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Privacy Policy
                                </a>
                            </li>
                        </ul>

                    </div>

                    <div class="col-lg-6 col-xl-3">

                        <h6 class="fw-bold mb-3">Our Services</h6>

                        <ul class="nav flex-column">
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Home
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    About Us
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Services
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Term of Service
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-danger me-1"></i>
                                    Privacy Policy
                                </a>
                            </li>
                        </ul>

                    </div>

                    <div class="col-lg-6 col-xl-3">

                        <h6 class="fw-bold mb-3">Follow us of Social Media</h6>
                        <p>Monthly digest of what's new and exciting from us.</p>

                        <div class="social-links d-flex gap-2">

                            <a href="https://www.x.com" target="_blank" class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-x-twitter"></i>
                            </a>

                            <a href="https://www.facebook.com" target="_blank"
                                class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-facebook"></i>
                            </a>

                            <a href="https://www.instagram.com" target="_blank"
                                class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-instagram"></i>
                            </a>

                            <a href="https://www.skype.com" target="_blank"
                                class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-skype"></i>
                            </a>

                            <a href="https://www.linkedin.com" target="_blank"
                                class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-linkedin"></i>
                            </a>



                        </div>

                    </div>

                </div>

            </div>

        </div>

        <div class="copy-right bg-section">

            <div class="container">

                <div class="d-flex justify-content-between fs-7 py-3">

                    <div>
                        &copy; Copyright <span class="fw-bold">MibAX.</span> All Rights Reserved.
                    </div>

                    <div>
                        Designed By <a href="#" class="">MibAX</a>
                    </div>

                </div>

            </div>

        </div>

    </footer>

    <div class="back-to-top">
        <a href="#" title="Back to Top">
            <i class="fa-solid fa-arrow-up"></i>
        </a>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.bootstrap5.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>